apiVersion: v1
kind: Template
labels:
  template: ${APP}-build
metadata:
  name: ${APP}-build
objects:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: ${APP}
    name: ${APP}
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${APP}:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: git@github.com:${ORG}/${APP}.git
#      sourceSecret:
#        name: ${APP}-git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: 'registry.access.redhat.com/ubi8/openjdk-8:latest'
      type: Docker
    triggers:
      - type: ConfigChange
      - github:
          secret: ${APP}-git-webhook
        type: GitHub
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: ${APP}
    name: ${APP}
  spec:
    lookupPolicy:
      local: false
parameters:
- description: App Name
  name: APP
  required: true
  value: springboot-items-api
- description: Organization
  name: ORG
  required: true
  value: michaelsteven
