apiVersion: v1
kind: Template
labels:
  template: ${APP}-deploy
metadata:
  name: ${APP}-deploy
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      app: ${APP}
    name: ${APP}
  spec:
    replicas: 1
    selector:
      app: ${APP}
      deploymentconfig: ${APP}
    strategy:
      resources: {}
    template:
      metadata:
          annotations:
            openshift.io/generated-by: OpenShiftNewApp
          creationTimestamp: null
          labels:
            app: ${APP}
            deploymentconfig: ${APP}
      spec:
        containers:
          - image: ${REGISTRY}/${APP}:latest
            name: ${APP}
            ports:
            - name: app-port
              containerPort: 8080
              protocol: TCP
            - name: liveness-port
              containerPort: 9001
              protocol: TCP
            resources:
              limits:
                #cpu: "2"
                cpu: "0.5"
                memory: 385Mi
              requests:
                cpu: "0.5"
                memory: 308Mi
            #args:
            #- -cpus
            #- "2"
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /actuator/health
                port: liveness-port
                scheme: HTTP
              initialDelaySeconds: 60
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 5
            livenessProbe:
              failureThreshold: 10
              httpGet:
                path: /actuator/health
                port: liveness-port
                scheme: HTTP
              initialDelaySeconds: 130
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 5
            env:
              - name: spring_config_location
                value: /config/application.yaml
              - name: spring_profiles_active
                value: kubernetes
              - name: mysql_username
                valueFrom:
                  secretKeyRef:
                    key: username
                    name: mysql-credentials
              - name: mysql_password
                valueFrom:
                  secretKeyRef:
                    key: password
                    name: mysql-credentials
            volumeMounts:
              - mountPath: /config
                name: application-config
                readOnly: true
        volumes:
          - name: application-config
            configMap:
              name: ${APP}
              defaultMode: 438
              items:
              - key: application.yaml
                path: application.yaml
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
      test: false
      triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
          - ${APP}
          from:
            kind: ImageStreamTag
            name: ${APP}:latest
        type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: ${APP}
      name: ${APP}
  spec:
      ports:
      - name: 80-tcp
        port: 80
        protocol: TCP
        targetPort: 8080
      - name: 9001-tcp
        port: 9001
        protocol: TCP
        targetPort: 9001
      selector:
        app: ${APP}
        deploymentconfig: ${APP}
  status:
      loadBalancer: {}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ${APP}
    name: ${APP}
  spec:
    port:
      targetPort: 80-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: ${APP}
      weight: 100
    wildcardPolicy: None
parameters:
- description: App Name
  name: APP
  required: true
  value: springboot-items-api
- description: Container Registry
  name: REGISTRY
  value: image-registry.openshift-image-registry.svc:5000/michael-hepfer-dev