apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ template "releasetag" . }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-app
      port: {{ .Values.service.appPort }}
      targetPort: {{ .Values.service.appPort }}
      protocol: TCP
    - name: http-liveness
      port: {{ .Values.service.livenessPort }}
      targetPort: {{ .Values.service.livenessPort }}
      protocol: TCP
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
    version: {{ .Values.subset.version }}
