apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "name" . }}
spec:
  hosts:
    - {{ .Values.service.name }}
    - "{{ .Values.ingress.itemsPath }}"
  gateways:
    - "{{ .Values.ingress.gateway }}"
  http:
    - route:
        - destination:
#            subset: {{ .Values.subset.version }}
            host: {{ .Values.service.name }}
            port:
              number: {{ .Values.service.appPort }}
          weight: 100
      timeout: 10s
