apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "240"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "240"
spec:
  rules:
    - host: {{ .Values.ingress.itemsPath }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.appPort }}                    
  tls:
    - secretName: {{ .Values.ingress.tlsSecretName }}
      hosts: 
        - {{ .Values.ingress.itemsPath }}